name: Wpm

on:
  push:
    branches:
      - 03_02e

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Iniciar sesión en Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Verificar archivos en el runner
        run: |
          echo "Listando archivos en el directorio raíz del workspace:"
          ls -R $GITHUB_WORKSPACE

      - name: Construir y enviar imagen Docker
        run: |
          docker build -f src/Wpm.Management.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:latest -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }} src/
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}
